import { ListView } from "std-widgets.slint";
import { MacroEconData, UpDown, ProductDemand } from "../../../state.slint";
import { Palette } from "../../../theme.slint";
import { Globs } from "../../../globals.slint";

import { TabContent } from "./tab-content.slint";
import { DataTable } from "../../common/datatable.slint";
import { CellData } from "../../common/datacell.slint";
import { PanelTitle } from "../../common/panel-title.slint";
import { Spacer } from "../../common/spacer.slint";

component DemandItem {
	in property <ProductDemand> pd;

	Rectangle {
		background: Palette.bg_lightgray;
		VerticalLayout {
			padding: 8px;
			Text {
				text: pd.product_name + " demand " + pd.percent + "%, since " + pd.age + " hours and " + pd.demand_met + "% is met.";
				font-size: 9px;
				horizontal-alignment: left;
				wrap: word-wrap;
				font-weight: 700;
			}
		}
	}
}

export component EconomyTab inherits TabContent {
	in property <MacroEconData> macroecon: Globs.macroecon;

	VerticalLayout {
		height: 100%;
		VerticalLayout {
			height: 10%;
			DataTable {
				title: "Macroeconomics";
				items: [
					{
						label: "Inflation rate",
						value: macroecon.inflation-rate.to-fixed(2),
						value_postfix: " %",
					},
					{
						label: "Inflation direction",
						value: macroecon.inflation-direction == UpDown.Up ? "Up" : "Down",
					},
					{
						label: "Fuel price",
						value: macroecon.fuel-price.to-fixed(2),
						value_postfix: " ϟ",
					},
				];
			}
		}

		VerticalLayout {
			height: 90%;
			PanelTitle {
				txt: "Product Demands";
			}

			Spacer {}

			ListView {
				height: 100%;
				for pd in Globs.product_demands: DemandItem {
					pd: pd;
				}
/*
				for pd in [
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
					{
						product_name: "Test Name",
						percent: 45.55555,
						age: 6,
						demand_met: 0.5,
					},
				] : DemandItem {
					pd: pd;
				}
*/
			}
		}
	}
}