use crate::simulation::{SimFlo, SimInt};

// SOLAR PANELS
pub const SOLAR_PANEL_PRICE: SimFlo = 1200.0;
pub const SOLAR_PANEL_MAX_AGE: SimInt = 10;
pub const SOLAR_PANEL_AGE_MODIFIER: SimInt = 10;

// POVVER PLANT
pub const PP_INIT_MONEY: SimFlo = 66000.0;
pub const PP_INIT_FUEL_CAPACITY: SimInt = 25;
pub const PP_INIT_PRODUCTION_CAP: SimInt = 24000;
pub const PP_INIT_FUEL_BUY_THRESHOLD: SimInt = 15;
pub const PP_FUEL_CAPACITY_INCREASE_COST: SimFlo = 10000.0;
pub const PP_FUEL_CAPACITY_INCREASE: SimInt = 25;
pub const PP_PRODUCTION_CAPACITY_INCREASE_COST: SimFlo = 25000.0;
pub const PP_PRODUCTION_CAPACITY_INCREASE: SimInt = 12000;
pub const PP_ENERGY_PER_FUEL: SimInt = 1000;

// FACTORY
pub const FACTORY_INIT_MONEY: SimFlo = 33000.0;
pub const FACTORY_MAX_SOLAR_PANELS: usize = 100;