[package]
name = "povver"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
rand = "0.8.5"
slint = "1.9.2"

[build-dependencies]
slint-build = "1.9.2"

[env]
SLINT_BACKEND = "winit-femtovg"