import { ActiveTab, SunStage, LogMessage, MessageSource, LogLevel } from "../../state.slint";
import { Globs, GlobCallbacks } from "../../globals.slint";
import { MapItem } from "../common/map-item.slint";
import { TalkBaloon } from "../common/talkbaloon.slint";

export component Factory inherits MapItem {
	in property <int> id;

	property <SunStage> sun_stage: Globs.env.the_sun.stage;

	property <[LogMessage]> messages: Globs.category_messages.factory[id];
	property <int> last_msg_index: messages.length - 1;
	property <LogMessage> last_message: messages[last_msg_index];
	property <bool> baloon_shown: false;

	init => {
		debug("FACTORY NO: " + id + " INITIALIZED");
	}

	timer := Timer {
		interval: 100ms;
		running: false;
		triggered => {
			baloon_shown = true;
			self.running = false;
		}
	}

	changed last_msg_index => {
		baloon_shown = false;
		timer.running = true;
	}

	Image {
		source: sun_stage ==
			SunStage.Set ? @image-url("../../images/factory-night.svg") :
			sun_stage == SunStage.Weak ?
			@image-url("../../images/factory-dawndusk.svg") :
			@image-url("../../images/factory.svg");
		width: 200px;
	}

	TalkBaloon {
		y: 30px;
		x: 220px;
		msg: last_message;
		is_shown: baloon_shown;
	}
}