import { SunStage } from "../../state.slint";
import { Globs } from "../../globals.slint";
import { Palette } from "../../theme.slint";

import { Sky } from "./sky.slint";

export component Map inherits Rectangle {
    width: 80%;
    height: 100%;

	property <SunStage> sun_stage: Globs.state.env.the_sun.stage;
	property <float> sun_brightness: Globs.state.env.the_sun.brightness;

	Rectangle {
		height: 100%;
		background: sun_stage == SunStage.Set ? Palette.sky_night :
			sun_stage == SunStage.Weak ? Palette.sky_setting :
			sun_stage == SunStage.Normal ? Palette.sky_normal :
			Palette.sky_bright;

		animate background {
			duration: 200ms;
		}

		Sky {}

		// Brightness filter for the whole scene
		// Depends on sun brightness
		Rectangle {
			property<float> opaque: ((100 - sun_brightness) / 100) * 0.5;
			background: rgba(0, 0, 0, opaque);
			animate background {
				duration: 200ms;
			}
		}
	}
}
