import { SunStage } from "../../state.slint";
import { Globs } from "../../globals.slint";
import { Palette } from "../../theme.slint";

import { Sky } from "./sky.slint";
import { Ground } from "./ground.slint";

import { PovverPlant } from "./pp.slint";
import { Factory } from "factory.slint";

export component Map inherits Rectangle {
    width: 80%;
    height: 100%;

	property <SunStage> sun_stage: Globs.env.the_sun.stage;
	property <float> sun_brightness: Globs.env.the_sun.brightness;

	Rectangle {
		height: 100%;
		background: sun_stage == SunStage.Set ? Palette.sky_night :
			sun_stage == SunStage.Weak ? Palette.sky_setting :
			sun_stage == SunStage.Normal ? Palette.sky_normal :
			Palette.sky_bright;

		animate background {
			duration: 200ms;
		}

		Sky {}

		Image {
			z: 1;
			y: 100px;
			source: @image-url("../../images/mountains.svg");
		}

		Ground {}

		PovverPlant {
			x: 100px;
			y: 750px;
			z: 4;
		}

		Factory {
			x: 50px;
			y: 350px;
			z: 4;
		}

		// Brightness filter for the whole scene
		// Depends on sun brightness
		Rectangle {
			z: 2;
			property <float> sb: sun_brightness / 100;
			property <float> opaque: sb == 0 ? 0.95 : 1 - sb;
			background: rgba(0, 0, 0, opaque);
			animate background {
				duration: 200ms;
			}
		}
	}
}
