import { SunStage, CloudSize, WindDirection, WindSpeedLevel } from "../../state.slint";
import { Globs } from "../../globals.slint";

export component Sky inherits Rectangle {
    height: 100px;
	width: 100%;
	y: 0;

	Image {
		property <int> pos: Globs.env.the_sun.position;
		property <SunStage> sun_stage: Globs.env.the_sun.stage;

		opacity: pos > -1 && pos < 17 ? 1 : 0;

		source: sun_stage == SunStage.Weak ? @image-url("../../images/sun-weak.svg") :
			sun_stage == SunStage.Normal ? @image-url("../../images/sun.svg") :
			sun_stage == SunStage.Bright ? @image-url("../../images/sun-bright.svg") :
			@image-url("../../images/sun-weak.svg");
		x: (parent.width / 16) * pos;

		animate x, opacity {
			duration: 200ms;
		}
	}

	for cloud in Globs.env.clouds: Image {
		source: cloud.size == CloudSize.Small ? Globs.cloud_images.small[cloud.image_index] :
			cloud.size == CloudSize.Medium ? Globs.cloud_images.medium[cloud.image_index] :
			Globs.cloud_images.big[cloud.image_index];

		rotation-angle: cloud.image_rotated ? 180deg : 0deg;
		width: 64px;
		x: (parent.width / 16) * cloud.position;

		animate x {
			duration: 100ms;
		}
	}

	// Wind indicator
	HorizontalLayout {
		property <WindDirection> wind_direction: Globs.env.wind_direction;
		property <WindSpeedLevel> wind_level: Globs.env.wind_speed_level;

		height: 64px;
		alignment: wind_direction == WindDirection.Ltr ? start : end;

		Image {
			source: wind_direction == WindDirection.Ltr ?
				wind_level == WindSpeedLevel.Faint ? @image-url("../../images/wind-ltr-faint.svg") :
				wind_level == WindSpeedLevel.Mild ? @image-url("../../images/wind-ltr-mild.svg") :
				wind_level == WindSpeedLevel.Strong ? @image-url("../../images/wind-ltr-strong.svg") :
				@image-url("../../images/wind-ltr-typhoon.svg")
			:
				wind_level == WindSpeedLevel.Faint ? @image-url("../../images/wind-rtl-faint.svg") :
				wind_level == WindSpeedLevel.Mild ? @image-url("../../images/wind-rtl-mild.svg") :
				wind_level == WindSpeedLevel.Strong ? @image-url("../../images/wind-rtl-strong.svg") :
				@image-url("../../images/wind-rtl-typhoon.svg");
		}
	}
}