import { Button } from "std-widgets.slint";

import { ActiveTab } from "../../state.slint";
import { Globs } from "../../globals.slint";
import { Palette } from "../../theme.slint";

import { TabButton } from "../common/tab-button.slint";

import { EnvironmentTab } from "./tab-contents/environment.slint";
import { EconomyTab } from "./tab-contents/economy.slint";
import { IndustriesTab } from "./tab-contents/industries.slint";
import { PovverPlantTab } from "./tab-contents/povver-plant.slint";
import { EventsTab } from "./tab-contents/events.slint";

export component PanelTabs inherits Rectangle {
	background: Palette.bg_darkgray;
    in-out property <ActiveTab> active-tab <=> Globs.active_cp_tab;

    VerticalLayout {
        height: 100%;
        width: 100%;
        tab_bar := HorizontalLayout {
            spacing: 3px;
            TabButton {
                is-active: root.active-tab == ActiveTab.Events;
				button-text: "Events";
                clicked => { root.active-tab = ActiveTab.Events; }
            }
            TabButton {
                is-active: root.active-tab == ActiveTab.Env;
				button-text: "Environment";
                clicked => { root.active-tab = ActiveTab.Env; }
            }
            TabButton {
                is-active: root.active-tab == ActiveTab.Economy;
				button-text: "Economy";
                clicked => { root.active-tab = ActiveTab.Economy; }
            }
            TabButton {
                is-active: root.active-tab == ActiveTab.Industries;
				button-text: "Industries";
                clicked => { root.active-tab = ActiveTab.Industries; }
            }
            TabButton {
                is-active: root.active-tab == ActiveTab.PP;
				button-text: "Povver Plant";
                clicked => { root.active-tab = ActiveTab.PP; }
            }
        }

        VerticalLayout {
            padding-top: 16px;
            padding-bottom: 16px;
            padding-left: 8px;
            padding-right: 8px;
			Rectangle {
				clip: true;
				EventsTab {
					x: root.active-tab == ActiveTab.Events ? 0 : parent.width + 1px;
				}
				EnvironmentTab {
					x: root.active-tab == ActiveTab.Env ? 0 : parent.width + 1px;
				}
				EconomyTab {
					x: root.active-tab == ActiveTab.Economy ? 0 : parent.width + 1px;
				}
				IndustriesTab {
					x: root.active-tab == ActiveTab.Industries ? 0 : parent.width + 1px;
				}
				PovverPlantTab {
					x: root.active-tab == ActiveTab.PP ? 0 : parent.width + 1px;
				}
			}
        }
    }
}
