import { Palette } from "../../theme.slint";
import { PanelTitle } from "panel-title.slint";

export struct CellData {
	label: string,
	value: string,
	value_postfix: string,
	is_category: bool,
}

export component DataCell inherits HorizontalLayout {
	in property <CellData> data;
	in property <color> text-color: white;

	alignment: space-between;

	if data.is_category : PanelTitle {
		txt: data.label;
	}
	if !data.is_category :
		Text {
			color: text-color;
			text: data.label;
		}
		Text {
			color: text-color;
			text: data.value + data.value_postfix;
		}
}