import { GlobCallbacks, Globs } from "./globals.slint";
import { UIState, CloudData, SunStage } from "./state.slint";

import { Utils } from "./utils.slint";

import { Map } from "./components/map/map.slint";
import { ControlPanel } from "./components/control-panel/control-panel.slint";

import "./fonts/digital-7.ttf";
import "./fonts/MonaspiceArNerdFont-Medium.otf";
import "./fonts/MonaspiceArNerdFont-Bold.otf";

export {
    UIState,
    CloudData,
    SunStage,
}

export component PovverMain inherits Window {
    default-font-family: "Monaspice Ar Nerd Font";
    title: "POVVER";

    in property <UIState> state <=> Globs.state;
    in property <[CloudData]> clouds <=> Globs.clouds;

	// Event callbacks
    pure callback toggle_pause <=> GlobCallbacks.toggle_pause;
    pure callback speed_change <=> GlobCallbacks.speed_change;

    HorizontalLayout {
        Map {}
        ControlPanel {}
    }
}
