import { GlobCallbacks, Globs } from "./globals.slint";
import {
	UIMisc,
	TimerData,
	MonthData,
	EnvData,
	MacroEconData,
	Date,
	Cloud,
	CloudSize,
	SunStage,
	WindDirection,
	WindSpeedLevel,
	LogMessage,
	LogLevel,
	MessageSource,
	CategoryMessages,
	ProductDemand
} from "./state.slint";

import { Utils } from "./utils.slint";

import { Map } from "./components/map/map.slint";
import { ControlPanel } from "./components/control-panel/control-panel.slint";

import "./fonts/digital-7.ttf";
import "./fonts/MonaspiceArNerdFont-Medium.otf";
import "./fonts/MonaspiceArNerdFont-Bold.otf";

export {
    UIMisc,
    Date,
    MonthData,
    Cloud,
    CloudSize,
    SunStage,
    WindDirection,
    WindSpeedLevel,
    LogMessage,
    LogLevel,
    MessageSource,
    CategoryMessages,
    ProductDemand
}

export component PovverMain inherits Window {
    default-font-family: "Monaspice Ar Nerd Font";
    title: "POVVER";

    in property <TimerData> timer <=> Globs.timer;
    in property <MonthData> month <=> Globs.month;
    in property <EnvData> env <=> Globs.env;
    in property <MacroEconData> macroecon <=> Globs.macroecon;
    in property <UIMisc> misc <=> Globs.misc;
    in property <[LogMessage]> messages <=> Globs.messages;
    in property <CategoryMessages> category_messages <=> Globs.category_messages;
    in property <[ProductDemand]> product_demands <=> Globs.product_demands;

	// Event callbacks
    pure callback toggle_pause <=> GlobCallbacks.toggle_pause;
    pure callback speed_change <=> GlobCallbacks.speed_change;

    HorizontalLayout {
        Map {}
        ControlPanel {}
    }
}
