export struct Date {
   minute: int,
   hour: int,
   day: int,
   month: int,
   year: int,
}

export struct TimerData {
    date: Date,
}

export enum SunStage {
	Set,
	Weak,
	Normal,
	Bright
}

struct SunData {
	position: int,
	brightness: float,
	stage: SunStage,
}

export enum CloudSize {
	Small,
	Medium,
	Big
}

export struct Cloud {
	size: CloudSize,
	position: int,
	image_index: int,
	image_rotated: bool,
}

export enum WindDirection {
	Ltr,
	Rtl
}

export enum WindSpeedLevel {
    Faint,
    Mild,
    Strong,
    Typhoon
}

export struct EnvData {
	the_sun: SunData,
	wind_speed: int,
	wind_direction: WindDirection,
	wind_speed_level: WindSpeedLevel
}

export struct UIState {
    timer: TimerData,
    env: EnvData,
    is_paused: bool,
    speed_index: int,
}
