// TIMER
export struct Date {
   minute: int,
   hour: int,
   day: int,
   month: int,
   year: int,
}

export struct TimerData {
    date: Date,
}

// ENVIRONMENT
export struct MonthData {
    day_start: int,
    day_end: int,
    name: string,
    sunshine_factor: float,
    windspeed_factor: float,
    cloud_forming_factor: float,
}

export enum SunStage {
	Set,
	Weak,
	Normal,
	Bright
}

struct SunData {
	position: int,
	brightness: float,
	brightness_reduction: float,
	stage: SunStage,
}


export enum CloudSize {
	Small,
	Medium,
	Big
}

export struct Cloud {
	size: CloudSize,
	position: int,
	image_index: int,
	image_rotated: bool,
}

export enum WindDirection {
	Ltr,
	Rtl
}

export enum WindSpeedLevel {
    Faint,
    Mild,
    Strong,
    Typhoon
}

export struct EnvData {
	the_sun: SunData,
	wind_speed: int,
	wind_direction: WindDirection,
	wind_speed_level: WindSpeedLevel,
	clouds: [Cloud],
}

// ECONOMY
export enum UpDown {
	Up,
	Down
}

export struct MacroEconData {
	inflation_rate: float,
	inflation_direction: UpDown,
	fuel_price: float
}

export struct ProductDemand {
	product_name: string,
	percent: float,
	age: int,
	demand_met: float,
}

// LOG MESSAGES
export enum MessageSource {
	Hub,
	PP,
	Factory
}

export enum LogLevel {
	Info,
	Warning,
	Critical
}

export struct LogMessage {
	source: MessageSource,
	message: string,
	level: LogLevel,
	factory_id: int,
}

export struct CategoryMessages {
	hub: [LogMessage],
	pp: [LogMessage],
	factory: [LogMessage],
}

// MISC
export struct UIMisc {
    is_paused: bool,
    speed_index: int,
}
