export global Palette {
	// Backgrounds
    out property<color> bg_darkgray: #111111;
    out property<color> bg_lightgray: #cccccc;
    out property<color> bg_lcd: #330008;
    out property<color> fg_lcdtext: #FF0000;
    // Sky colors
    out property <color> sky_bright: #cfecf7;
    out property <color> sky_normal: #a0d9ef;
    out property <color> sky_setting: #5781f4;
    out property <color> sky_night: #0c1040;
    // Highlights
    out property <color> bright_text: #DDDDDD;

    // Log level colors
    out property <color> log_info: #4CAF50;
    out property <color> log_warn: #FFD700;
    out property <color> log_critical: #FF6F61;
}